### PR TITLE
remove _mut methods, remove claim, add Priority.as_ceiling

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4e6818e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4e6818e with merge 4e6818e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/224010032)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0a6583d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0a6583d with merge 0a6583d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/224014852)
Approved by: japaric
Pushing 0a6583ddc6909215e5db10e8df9da48cc7bffe1a to master...

**Pull request merged**
