### PR TITLE
simplify the tasks! macro, make the `request` function more straightforward

### PR DESCRIPTION
**Pull request by japaric**
in its meaning

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 67881bc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 67881bc with merge 67881bc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/221213056)
Approved by: japaric
Pushing 67881bc7f552a58a2a373fc3b7f59f5775d3eaec to master...

**Pull request merged**
