### PR TITLE
lock_mut and more cfail tests

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cc6c1ad has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cc6c1ad with merge cc6c1ad...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/221507845)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2d334e7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2d334e7 with merge 2d334e7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/221511648)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1ed5696 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1ed5696 with merge 1ed5696...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/221514588)
Approved by: japaric
Pushing 1ed5696f767ea3e9f8f990394936fe0ed4ce3c58 to master...

**Pull request merged**
