### PR TITLE
critical: don't let the ceiling token escape the critical section

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aee3c2b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aee3c2b with merge aee3c2b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/223702922)
Approved by: japaric
Pushing aee3c2b29b9c47d5b359cc8ef56fcd0d9a9ba15d to master...

**Pull request merged**
