### PR TITLE
don't let the ceiling token escape the critical section

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aee1d78 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aee1d78 with merge aee1d78...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/223687604)
Approved by: japaric
Pushing aee1d785a914365e64462ce507e27ca917da9055 to master...

**Pull request merged**
