### PR TITLE
improved `tasks!` macro, replaced `lock` with `raise`, etc.

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 59cff58 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 59cff58 with merge 59cff58...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e72687a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e72687a with merge e72687a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/225666239)
Approved by: japaric
Pushing e72687a36635ccfce494f8807269bf897b3b6d7b to master...

**Pull request merged**
