### PR TITLE
wrap references to resources in static-ref's Ref/RefMut

### PR DESCRIPTION
**Pull request by japaric**
to assert that they point to `static` data

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a94de6b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a94de6b with merge a94de6b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-srp/builds/222244515)
Approved by: japaric
Pushing a94de6bafcd95c0313e638138643f87c3b0e6aa0 to master...

**Pull request merged**
